### ISSUE TITLE
asyncio.exceptions.IncompleteReadError is not caught

### ISSUE THREAD

**Issue by Trolldemorted** [ldruschk/enochecker3#21]
Is there any documentation about which errors are caught automatically? This one apparently isn't:

```
Encountered internal exception:
Traceback (most recent call last):
  File "/home/checker/.local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 500, in checker
    return await self._call_putflag(
  File "/home/checker/.local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 314, in _call_putflag
    attack_info: Optional[str] = await self._call_method(task)
  File "/home/checker/.local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 294, in _call_method
    return await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/checker/.local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 290, in _call_method_raw
    return await f(*args)
  File "/checker/checker.py", line 257, in putflag_test
    async with BambiNoteClient(task) as client:
  File "/checker/checker.py", line 54, in __aenter__
    await self.reader.readuntil(BANNER)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 629, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of undefined expected bytes
```

**Comment by ldruschk** [comment]
should be fixed by #19
